### ISSUE TITLE
Yardım Eder Misiniz?

### ISSUE THREAD

**Issue by yavuzsel1m** [daswareinfach/Battleye-VAC-EAC-Kernel-Bypass#1]
Projeyi vs 2017 ile açıp başlat butonuna tıkladığımda hata alıyorum. Projenin Buildlenmiş halini .exe formatında paylaşabilir misiniz? Aldığım hata: http://prntscr.com/ju2ejq

**Comment by daswareinfach** [comment]
Benden kaynaklı bir sorun gözükmüyor.
