### ISSUE TITLE
Get in contact with you. Not an issue.

### ISSUE THREAD

**Issue by WorldBala** [daswareinfach/Battleye-VAC-EAC-Kernel-Bypass#3]
Hi there,

I'd like to get in contact with you if possible. Would be happy to discuss a few private details. Couldn't find any contact info in your bio so I am writing here.

**Comment by MeroZemory** [comment]
Please keep in mind that this is not for personal contact and that your act of posting an issue will send a notification to everyone who subscribes to that repository.

**Comment by daswareinfach** [comment]
Done
